### ISSUE TITLE
Avoid mis-pressing of screen buttons after update/reload

### ISSUE THREAD

**Issue by johnnyfoe** [JamiePrentice/EloEloElo#20]
The previous version of the software allowed out of date info to be submitted. @JamiePrentice fixed the issue by setting the page to auto-refresh when using a mobile device coming out of standby/screen lock.

This issue has been reintroduced with the new software.

The main issue with this is that when people come back to the screen they don't see buttons related to the current game, instead they see the previous game's results.

The previous software also disabled buttons for x seconds after any update/page load to ensure that the most current information was displayed and understood prior to allowing button presses.

**Comment by DavidChristiansen** [comment]
Already fixed. Deployed in next release
